#!/usr/bin/env python3
import argparse
import random
import sqlite3
import sys
from pathlib import Path

TARGET_FILE = Path("spec") / "queries" / "metadata_params.txt"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Extract deterministic metadata queries for benchmarks."
    )
    parser.add_argument(
        "workspace",
        type=Path,
        help="Path to the stage_1 workspace (must contain datamarts/metadata.db)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if the committed file matches the generated data.",
    )
    return parser


def format_params(
        authors: list[str],
        book_ids: list[int],
        prefixes: list[str],
        languages: list[str],
) -> str:
    """Format the extracted parameters into a simple line format."""
    lines = [
        "# Generated by tools/make_metadata_params.py",
        "# Do not edit manually.",
        "",
        "# Q1: Exact author matches",
        *[f"Q1={author}" for author in authors],
        "",
        "# Q2: Exact book ID lookups",
        *[f"Q2={book_id}" for book_id in book_ids],
        "",
        "# Q3: Title prefix matches",
        *[f"Q3={prefix}" for prefix in prefixes],
        "",
        "# Q4: Exact language matches",
        *[f"Q4={lang}" for lang in languages],
        ""
    ]
    return "\n".join(lines)


def main():
    args = build_parser().parse_args()
    db_path = args.workspace / "datamarts" / "metadata.db"

    if not db_path.exists():
        print(f"Error: Database not found at {db_path}", file=sys.stderr)
        sys.exit(1)

    # Fixed seed AND a fixed input order (every query has ORDER BY): the same
    # database must always give the same file, or --check is meaningless (SPEC §5.4).
    rng = random.Random(42)

    with sqlite3.connect(db_path) as conn:
        conn.row_factory = sqlite3.Row

        # Q1: 100 random authors (some might be NULL in DB, filter them out)
        all_authors = [r["author"] for r in
                       conn.execute("SELECT DISTINCT author FROM books WHERE author IS NOT NULL ORDER BY author").fetchall()]
        rng.shuffle(all_authors)
        selected_authors = all_authors[:100]

        # Q2: 100 random book IDs
        all_ids = [r["book_id"] for r in conn.execute("SELECT book_id FROM books ORDER BY book_id").fetchall()]
        rng.shuffle(all_ids)
        selected_ids = all_ids[:100]

        # Q3: 100 random title prefixes (first 10 chars)
        all_titles = [r["title"] for r in conn.execute("SELECT title FROM books ORDER BY book_id").fetchall()]
        # sorted(): iterating a set of str depends on PYTHONHASHSEED, which made
        # every run (and --check) produce a different order.
        prefixes = sorted({title[:10] for title in all_titles if len(title) >= 10})
        rng.shuffle(prefixes)
        selected_prefixes = prefixes[:100]

        # Q4: 10 random languages
        all_langs = [r["language"] for r in
                     conn.execute("SELECT DISTINCT language FROM books WHERE language IS NOT NULL ORDER BY language").fetchall()]
        rng.shuffle(all_langs)
        selected_langs = all_langs[:10]

    content = format_params(
        selected_authors,
        selected_ids,
        selected_prefixes,
        selected_langs
    )

    TARGET_FILE.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        if not TARGET_FILE.exists():
            print(f"Error: {TARGET_FILE} does not exist.", file=sys.stderr)
            sys.exit(2)

        existing_content = TARGET_FILE.read_text(encoding="utf-8")
        if existing_content != content:
            print(f"Error: {TARGET_FILE} differs from the generator.", file=sys.stderr)
            sys.exit(3)

        print("Check passed: committed file matches generator.")
        sys.exit(0)

    TARGET_FILE.write_text(content, encoding="utf-8", newline="\n")
    print(f"Successfully wrote {TARGET_FILE}.")


if __name__ == "__main__":
    main()